CREATE TABLE batches (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    event VARCHAR NOT NULL,
    total INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE reservations (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL,
    quantity INT NOT NULL,
    status VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    batch_id UUID NOT NULL,
    CONSTRAINT fk_reservations_batch FOREIGN KEY (batch_id) REFERENCES batches(id) ON DELETE CASCADE
);
